import argparse
from typing import Generator

def get_parser() -> argparse.ArgumentParser: ...
def all_commands() -> Generator[str, None, None]: ...
def available_commands() -> str: ...
def run(*args: str) -> int: ...
